/* This is a dictionary of the language defined functions
**/
export default {
  main_function: "inicio",
  $read: "leia",
  $write: "escreva",
  $numElements: "total_de_elementos",
  $matrixLines: "total_de_linhas",
  $matrixColumns: "total_de_colunas",
  $substring: "subcadeia",
  $length: "comprimento",
  $uppercase: "caixa_alta",
  $lowercase: "caixa_baixa",
  $charAt: "texto_na_posicao",
  $isReal: "e_real",
  $isInt: "e_inteiro",
  $isBool: "e_logico",
  $castReal: "como_real",
  $castInt: "como_inteiro",
  $castBool: "como_logico",
  $castString: "como_cadeia",
  $sin: "seno",
  $cos: "cosseno",
  $tan: "tangente",
  $sqrt: "raiz_quadrada",
  $pow: "potencia",
  $log: "logaritmo",
  $abs: "modulo",
  $negate: "trocar_sinal",
  $invert: "inverter_valor",
  $max: "maximo",
  $min: "minimo",
  $rand: "numero_aleatorio"
}