/* This is a dictionary of the language defined functions
**/
export default {
  main_function: "inicio",
  $read: "leia",
  $write: "escreva",
  $numElements: "numero_elementos",
  $matrixLines: "matriz_linhas",
  $matrixColumns: "matriz_colunas",
  $substring: "subcadeia",
  $length: "comprimento",
  $uppercase: "caixa_alta",
  $lowercase: "caixa_baixa",
  $charAt: "char_at",
  $isReal: "e_real",
  $isInt: "e_inteiro",
  $isBool: "e_logico",
  $castReal: "como_real",
  $castInt: "como_inteiro",
  $castBool: "como_logico",
  $castString: "como_cadeia",
  $sin: "sen",
  $cos: "cos",
  $tan: "tan",
  $sqrt: "raiz_quadrada",
  $pow: "pot",
  $log: "log",
  $abs: "modulo",
  $negate: "trocar_sinal",
  $invert: "inverter_valor",
  $max: "maximo",
  $min: "minimo"
}
